<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-8 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>

    			<div class="title_white row">

					TCC

				</div>

    			<div class="subtitle_white row">

    				 <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
  						<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z"/>
					</svg>

					Lista para Gestão de Tarefas

				</div>
				

			</div>
		</div>
    </div>

    <div class="col-md-4 pt-4 pl-5 pr-5">


    <div class="card" >
      <div class="card-body">

	    <div class="row">
			<div class="col">
					<form method="post" action="/autenticar">

							<?php if($this->view->login == 'erro') { ?>
								<span class="text text-danger mb-2">*E-mail e ou senha inválido(s)</span>
							<?php } ?>


						
							<input type="text" name="email" class="form-control mb-2" placeholder="E-mail">
						
							<input type="password" name="senha" class="form-control mb-2" placeholder="Senha">

							

							<button type="submit" class="btn btn-outline-primary" style="width: 100%;">Entrar</button>

					</form>


					<h2 class="subtitle" style="text-align: center;">Ou</h2>
					<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>

			</div>
		</div>

		</div>
	</div>


    </div>

  </div>
</div>