    <nav class="navbar navbar-expand-lg menu">
        <div class="container">
            <div class="navbar-nav menu">


                        <a class="menuItem" href="/timeline">Home</a>
                        <a class="menuItem" href="/perfil">Minhas Tarefas</a>
                        <a class="menuItem" href="/sair">Sair</a>

                        <div class="menuItem">
                                <form method="get" action="/quem_seguir">
                                    <div class="input-group">
                                        <input type="text" name="pesquisarPor" class="form-control" placeholder="Pesquisar ..">
                                        <div class="input-group-append">
                                            <button class="btn btn-secondary" type="submit"><i class="fas fa-search"></i></button>
                                        </div>
                                    </div>
                                </form>
                        </div>
                </div>
            </div>
        </div>
    </nav>