<?php
	// Lê a mensagem da URL 
$mensagem = isset($_GET['mensagem']) ? $_GET['mensagem'] : '';
?>

<?php include 'navbar.phtml'; ?>

<div class="container mt-5">
	<div class="row pt-2 justify-content-center"> <!-- Adicionado a classe justify-content-center -->
		
		<div class="col-md-6">

			<div class="row perfilPainel" style="margin-Top: 30px;">
				<div class="col">
					
					<div class="row">
						<div class="col">
							<span class="perfilPainelNome">
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row">

						<div class="col">
							<span class="perfilPainelItem">Tarefas</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tarefas['total_tarefa'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguindo['total_seguindo'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores['total_seguidores'] ?>
							</span>
						</div>

						<div>

							<?php if(isset($_GET['id_usuario']) && $_GET['id_usuario'] != $_SESSION['id']){
								if($this->view->seguindo_sn == 0) { ?>
									<a href="/seguir?acao=seguir&id_usuario=<?=$_GET['id_usuario']?>"
										class="btn btn-outline-primary">Seguir</a>
								<?php } else { ?>
									<a href="/seguir?acao=deixar_de_seguir&id_usuario=<?=$_GET['id_usuario']?>"
										class="btn btn-outline-danger">Deixar de seguir</a>
								<?php }
							}?> 

						</div>

					</div>

					<hr/>
				</div>
			</div>


			<div class="row mb-4">
				<div class="col">
					<span class="notificacao text text-danger"><?php echo $mensagem; ?> </span>
				</div>
			</div>

			<?php foreach($this->view->tarefas as $id_tarefa => $tarefa) { ?>
				<div class="row tarefa mb-1">
					<div class="col">
						<p><strong><?=$tarefa['titulo']?></strong></p>
						<p><?=$tarefa['descricao']?></p>
						<p><small> <strong><?=$tarefa['nome']?></strong> -
							<span class="text text-muted"><?=$tarefa['data']?>
							- <?php if (isset($tarefa['dataConclusao'])) {
								echo $tarefa['dataConclusao'];
							} else {
								echo $tarefa['s_situacao'];
							} ?></span></small></p>

							<br />
							<?php if($tarefa['id_usuario'] == $_SESSION['id']) { ?>
								<form>
									<div class="col d-flex justify-content-end align-items-center">

										<div class="mr-2">
											<a href="/removetarefa?acao=remover&id_tarefa=<?=$tarefa['id']?>"
												class="btn btn-outline-danger">Excluir</a>
											</div>

											<div class="mr-2">
												<?php if($tarefa['t_situacao'] == 1) { ?>

													
													<a href="/concluirtarefa?acao=concluir&id_tarefa=<?=$tarefa['id']?>"
														class="btn btn-primary">Concluir</a>

													<?php } else if($tarefa['t_situacao'] == 2) {?>

														<a class="btn btn-secondary disabled">Concluida</a>

													<?php }?>
												</div>
											</div>
										</form>
									<?php } ?>
								</div>
							</div>
						<?php } ?>


					<div class="row mb-4">
					    <nav aria-label="..." class="mt-3">
					        <ul class="pagination">
					            <?php
					            // Verifica se o ID do usuário está presente na URL
					            $id_usuario_parametro = isset($_GET['id_usuario']) ? '&id_usuario=' . $_GET['id_usuario'] : '';

					            // Loop para exibir os links da paginação
					            for ($i = 1; $i <= $this->view->total_de_paginas; $i++) :
					                ?>
					                <li class="page-item <?= (!isset($_GET['pagina']) && $i === 1) || (isset($_GET['pagina']) && $_GET['pagina'] == $i) ? 'active' : '' ?>">
					                    <!-- Adiciona o ID do usuário como parâmetro na URL da página -->
					                    <a class="page-link" href="?pagina=<?= $i . $id_usuario_parametro ?>"><?= $i ?></a>
					                </li>
					            <?php endfor; ?>
					        </ul>
					    </nav>
					</div>

					</div>
				</div>
