
<?php
// Lê a mensagem da URL 
$mensagem = isset($_GET['mensagem']) ? $_GET['mensagem'] : '';
?>

<?php include 'navbar.phtml'; ?>

<div class="container mt-5">
	<div class="row pt-2 justify-content-center">
		
		<div class="col-md-6">

			<div class="row mb-2">
				<div class="col tarefaBox" style="margin-Top: 30px;">

					<form method="post" action="/tarefa">
						<textarea class="form-control mb-1" name="titulo" id="titulo" rows="1" placeholder="* Titulo .."></textarea>
						<textarea class="form-control mb-1" name="descricao" id = "descricao" rows="3" placeholder="Descrição .."></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Publicar</button>
						</div>

					</form>

					<span class="text text-danger"><?php echo $mensagem; ?> </span>
				</div>
			</div>



			<?php foreach($this->view->tarefas as $id_tarefa => $tarefa) { ?>
				<div class="row tarefa mb-1">
					<div class="col">
						<p><strong><?=$tarefa['titulo']?></strong></p>
						<p><?=$tarefa['descricao']?></p>
						<p><small> <strong><?=$tarefa['nome']?></strong> -
							<span class="text text-muted"><?=$tarefa['data']?>
							- <?php if (isset($tarefa['dataConclusao'])) {
								echo $tarefa['dataConclusao'];
							} else {
								echo $tarefa['s_situacao'];
							} ?></span></small></p>
							<br />
						</div>
				</div>
			<?php } ?>

			<div class="row">
				<nav aria-label="..." class="mt-3">
					<ul class="pagination">
						<?php for ($i = 1; $i <= $this->view->total_de_paginas; $i++) : ?>
							<li class="page-item <?= (!isset($_GET['pagina']) && $i === 1) || (isset($_GET['pagina']) && $_GET['pagina'] == $i) ? 'active' : '' ?>">
								<a class="page-link" href="?pagina=<?= $i ?>"><?= $i ?></a>
							</li>
						<?php endfor; ?>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>